/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisPanel: typeof import('./src/components/AnalysisPanel.vue')['default']
    AnalyticsDisplay: typeof import('./src/components/userCabinet/AnalyticsDisplay.vue')['default']
    Chessboard: typeof import('./src/components/Chessboard.vue')['default']
    ChessboardPreview: typeof import('./src/components/ChessboardPreview.vue')['default']
    ClubPageHeader: typeof import('./src/components/clubPage/ClubPageHeader.vue')['default']
    ClubPageTabs: typeof import('./src/components/clubPage/ClubPageTabs.vue')['default']
    ClubStatsTable: typeof import('./src/components/clubPage/ClubStatsTable.vue')['default']
    ClubTrophies: typeof import('./src/components/clubPage/ClubTrophies.vue')['default']
    ConfirmationModal: typeof import('./src/components/ConfirmationModal.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    DetailedAnalytics: typeof import('./src/components/userCabinet/DetailedAnalytics.vue')['default']
    EngineSelector: typeof import('./src/components/EngineSelector.vue')['default']
    FinishHimSelection: typeof import('./src/components/FinishHimSelection.vue')['default']
    GameLayout: typeof import('./src/components/GameLayout.vue')['default']
    GlobalActivityStats: typeof import('./src/components/userCabinet/sections/GlobalActivityStats.vue')['default']
    InfoIcon: typeof import('./src/components/InfoIcon.vue')['default']
    InfoModal: typeof import('./src/components/InfoModal.vue')['default']
    LatestBattleReport: typeof import('./src/components/clubPage/LatestBattleReport.vue')['default']
    MedalStandingsTable: typeof import('./src/components/clubPage/MedalStandingsTable.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpin: typeof import('naive-ui')['NSpin']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    OpeningStatsTable: typeof import('./src/components/OpeningTrainer/OpeningStatsTable.vue')['default']
    OpeningTrainerHeader: typeof import('./src/components/OpeningTrainer/OpeningTrainerHeader.vue')['default']
    OpeningTrainerSettingsModal: typeof import('./src/components/OpeningTrainer/OpeningTrainerSettingsModal.vue')['default']
    PlayerStatsDetail: typeof import('./src/components/clubPage/PlayerStatsDetail.vue')['default']
    PromotionDialog: typeof import('./src/components/PromotionDialog.vue')['default']
    PuzzleInfo: typeof import('./src/components/PuzzleInfo.vue')['default']
    RadarChart: typeof import('./src/components/userCabinet/sections/RadarChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsMenu: typeof import('./src/components/SettingsMenu.vue')['default']
    SimpleLeaderboardTable: typeof import('./src/components/recordsPage/SimpleLeaderboardTable.vue')['default']
    SkillLeaderboardTable: typeof import('./src/components/recordsPage/SkillLeaderboardTable.vue')['default']
    StatsCard: typeof import('./src/components/userCabinet/sections/StatsCard.vue')['default']
    TelegramBinding: typeof import('./src/components/userCabinet/sections/TelegramBinding.vue')['default']
    TopInfoPanel: typeof import('./src/components/TopInfoPanel.vue')['default']
    TornadoHighScores: typeof import('./src/components/userCabinet/sections/TornadoHighScores.vue')['default']
    TornadoLeaderboardTable: typeof import('./src/components/recordsPage/TornadoLeaderboardTable.vue')['default']
    TornadoStats: typeof import('./src/components/TornadoStats.vue')['default']
    TournamentHistoryTable: typeof import('./src/components/clubPage/TournamentHistoryTable.vue')['default']
    TowerLeaderboardTable: typeof import('./src/components/recordsPage/TowerLeaderboardTable.vue')['default']
    TowerProgress: typeof import('./src/components/TowerProgress.vue')['default']
    TowerSelection: typeof import('./src/components/TowerSelection.vue')['default']
    UpcomingPositions: typeof import('./src/components/UpcomingPositions.vue')['default']
    UserProfileHeader: typeof import('./src/components/userCabinet/sections/UserProfileHeader.vue')['default']
    UserStats: typeof import('./src/components/UserStats.vue')['default']
    WinrateProgressBar: typeof import('./src/components/OpeningTrainer/WinrateProgressBar.vue')['default']
  }
}
