import type {
  LeaderboardApiResponse,
  PersonalActivityStatsResponse,
  UserProfileStatsDto,
  UserSessionProfile,
} from '../types/api.types'

export const EXAMPLE_USER_PROFILE: UserSessionProfile = {
  id: 'valid_all',
  username: 'VALID_ALL',
  perfs: {
    blitz: {
      rating: 1958,
      prog: 0,
      games: 0,
    },
  },
  createdAt: 1770792222695,
  profile: {},
  FunCoins: 100,
  subscriptionTier: 'King',
  TierExpire: null,
  tornadoHighScores: {
    bullet: 58,
    blitz: 26,
    rapid: 50,
    classic: 22,
  },
  validatedAt: 1770796114301,
  today_activity: {
    puzzles_solved_today: {
      tornado: 307,
      finishHim: 57,
      theory: 47,
      'practical-chess': 0,
      tacticalTrainer: 0,
      total: 411,
    },
  },
  endgame_skill: 1500,
}

export const EXAMPLE_ACTIVITY_STATS: PersonalActivityStatsResponse = {
  daily: {
    tornado: { puzzles_requested: 346, puzzles_solved: 345 },
    finish_him: { puzzles_requested: 55, puzzles_solved: 49 },
    theory: { puzzles_requested: 36, puzzles_solved: 34 },
    'practical-chess': { puzzles_requested: 26, puzzles_solved: 25 },
    repertoire: { puzzles_requested: 0, puzzles_solved: 0 },
    'diamond-hunter': { puzzles_requested: 0, puzzles_solved: 0 },
    'opening-sparring': { puzzles_requested: 0, puzzles_solved: 0 },
  },
  weekly: {
    tornado: { puzzles_requested: 3185, puzzles_solved: 3164 },
    finish_him: { puzzles_requested: 389, puzzles_solved: 338 },
    theory: { puzzles_requested: 311, puzzles_solved: 272 },
    'practical-chess': { puzzles_requested: 337, puzzles_solved: 294 },
    repertoire: { puzzles_requested: 0, puzzles_solved: 0 },
    'diamond-hunter': { puzzles_requested: 0, puzzles_solved: 0 },
    'opening-sparring': { puzzles_requested: 0, puzzles_solved: 0 },
  },
  monthly: {
    tornado: { puzzles_requested: 11751, puzzles_solved: 11646 },
    finish_him: { puzzles_requested: 1330, puzzles_solved: 1158 },
    theory: { puzzles_requested: 1219, puzzles_solved: 1080 },
    'practical-chess': { puzzles_requested: 1254, puzzles_solved: 1117 },
    repertoire: { puzzles_requested: 0, puzzles_solved: 0 },
    'diamond-hunter': { puzzles_requested: 0, puzzles_solved: 0 },
    'opening-sparring': { puzzles_requested: 0, puzzles_solved: 0 },
  },
}

export const EXAMPLE_DETAILED_STATS: UserProfileStatsDto = {
  tornado: {
    highScores: {
      bullet: 1412,
      blitz: 50,
      rapid: 67,
      classic: 42,
    },
    modes: {
      bullet: [
        { theme: 'pin', success: 46, requested: 50, rating: 2465 },
        { theme: 'deflection', success: 42, requested: 46, rating: 2444 },
        { theme: 'fork', success: 11, requested: 12, rating: 2421 },
        { theme: 'attraction', success: 1, requested: 1, rating: 2368 },
        { theme: 'discoveredAttack', success: 22, requested: 24, rating: 2333 },
        { theme: 'backRankMate', success: 30, requested: 32, rating: 2306 },
        { theme: 'skewer', success: 24, requested: 26, rating: 2247 },
        { theme: 'clearance', success: 11, requested: 12, rating: 2135 },
        { theme: 'interference', success: 45, requested: 49, rating: 2020 },
        { theme: 'capturingDefender', success: 19, requested: 20, rating: 1992 },
        { theme: 'quietMove', success: 4, requested: 4, rating: 1979 },
        { theme: 'doubleCheck', success: 43, requested: 47, rating: 1705 },
        { theme: 'promotion', success: 23, requested: 25, rating: 1675 },
        { theme: 'xRayAttack', success: 6, requested: 6, rating: 1628 },
        { theme: 'trappedPiece', success: 9, requested: 15, rating: 1447 },
      ],
      blitz: [
        { theme: 'trappedPiece', success: 49, requested: 53, rating: 2461 },
        { theme: 'promotion', success: 39, requested: 42, rating: 2433 },
        { theme: 'attraction', success: 24, requested: 26, rating: 2416 },
        { theme: 'clearance', success: 1, requested: 1, rating: 2382 },
        { theme: 'skewer', success: 11, requested: 12, rating: 2374 },
        { theme: 'pin', success: 13, requested: 14, rating: 2239 },
        { theme: 'deflection', success: 39, requested: 42, rating: 2236 },
        { theme: 'backRankMate', success: 7, requested: 7, rating: 2205 },
        { theme: 'fork', success: 1, requested: 1, rating: 2130 },
        { theme: 'discoveredAttack', success: 40, requested: 43, rating: 2081 },
        { theme: 'interference', success: 36, requested: 39, rating: 2043 },
        { theme: 'capturingDefender', success: 24, requested: 26, rating: 2037 },
        { theme: 'xRayAttack', success: 45, requested: 49, rating: 1832 },
        { theme: 'quietMove', success: 37, requested: 40, rating: 1779 },
        { theme: 'doubleCheck', success: 42, requested: 46, rating: 1746 },
      ],
      rapid: [
        { theme: 'discoveredAttack', success: 23, requested: 25, rating: 2402 },
        { theme: 'interference', success: 0, requested: 0, rating: 2399 },
        { theme: 'pin', success: 42, requested: 46, rating: 2285 },
        { theme: 'capturingDefender', success: 11, requested: 12, rating: 2080 },
        { theme: 'promotion', success: 47, requested: 51, rating: 2058 },
        { theme: 'xRayAttack', success: 21, requested: 23, rating: 1972 },
        { theme: 'backRankMate', success: 30, requested: 32, rating: 1856 },
        { theme: 'skewer', success: 13, requested: 14, rating: 1850 },
        { theme: 'quietMove', success: 30, requested: 32, rating: 1843 },
        { theme: 'doubleCheck', success: 15, requested: 16, rating: 1694 },
        { theme: 'deflection', success: 47, requested: 51, rating: 1683 },
        { theme: 'trappedPiece', success: 28, requested: 30, rating: 1650 },
        { theme: 'fork', success: 26, requested: 28, rating: 1634 },
        { theme: 'attraction', success: 23, requested: 25, rating: 1598 },
        { theme: 'clearance', success: 12, requested: 13, rating: 1532 },
      ],
      classic: [
        { theme: 'quietMove', success: 41, requested: 45, rating: 2462 },
        { theme: 'xRayAttack', success: 34, requested: 37, rating: 2270 },
        { theme: 'discoveredAttack', success: 6, requested: 6, rating: 2208 },
        { theme: 'capturingDefender', success: 23, requested: 25, rating: 2034 },
        { theme: 'interference', success: 0, requested: 0, rating: 1988 },
        { theme: 'doubleCheck', success: 15, requested: 16, rating: 1984 },
        { theme: 'fork', success: 3, requested: 3, rating: 1972 },
        { theme: 'promotion', success: 10, requested: 10, rating: 1881 },
        { theme: 'skewer', success: 18, requested: 19, rating: 1804 },
        { theme: 'deflection', success: 49, requested: 53, rating: 1749 },
        { theme: 'trappedPiece', success: 25, requested: 27, rating: 1704 },
        { theme: 'backRankMate', success: 39, requested: 42, rating: 1645 },
        { theme: 'pin', success: 14, requested: 15, rating: 1615 },
        { theme: 'attraction', success: 3, requested: 3, rating: 1615 },
        { theme: 'clearance', success: 30, requested: 32, rating: 1587 },
      ],
    },
  },
  finish_him: {
    modes: {
      novice: [
        { theme: 'knightBishop', rating: 1691, success: 19, requested: 26 },
        { theme: 'expert', rating: 1665, success: 5, requested: 7 },
        { theme: 'pawn', rating: 1560, success: 10, requested: 14 },
        { theme: 'rookPawn', rating: 1541, success: 23, requested: 32 },
        { theme: 'knight', rating: 1500, success: 1, requested: 1 },
        { theme: 'rookPieces', rating: 1486, success: 19, requested: 26 },
        { theme: 'queenPieces', rating: 1467, success: 22, requested: 30 },
        { theme: 'knight', rating: 1439, success: 19, requested: 26 },
        { theme: 'queen', rating: 1400, success: 10, requested: 14 },
        { theme: 'bishop', rating: 1318, success: 20, requested: 28 },
      ],
      pro: [
        { theme: 'queenPieces', rating: 1825, success: 1, requested: 1 },
        { theme: 'bishop', rating: 1694, success: 11, requested: 15 },
        { theme: 'knightBishop', rating: 1679, success: 16, requested: 22 },
        { theme: 'rookPieces', rating: 1649, success: 13, requested: 18 },
        { theme: 'rookPawn', rating: 1643, success: 15, requested: 21 },
        { theme: 'knight', rating: 1610, success: 5, requested: 7 },
        { theme: 'queen', rating: 1511, success: 26, requested: 36 },
        { theme: 'pawn', rating: 1475, success: 19, requested: 26 },
        { theme: 'expert', rating: 1456, success: 16, requested: 22 },
      ],
      master: [
        { theme: 'knight', rating: 1995, success: 18, requested: 25 },
        { theme: 'rookPieces', rating: 1855, success: 14, requested: 19 },
        { theme: 'rookPawn', rating: 1836, success: 26, requested: 36 },
        { theme: 'bishop', rating: 1833, success: 9, requested: 12 },
        { theme: 'queen', rating: 1779, success: 16, requested: 22 },
        { theme: 'expert', rating: 1745, success: 19, requested: 26 },
        { theme: 'queenPieces', rating: 1723, success: 9, requested: 12 },
        { theme: 'pawn', rating: 1703, success: 20, requested: 28 },
        { theme: 'knightBishop', rating: 1636, success: 20, requested: 28 },
      ],
    },
  },
  theory: {
    stats: {
      'win/novice/bishop': { success: 6, requested: 9 },
      'win/novice/knight': { success: 2, requested: 3 },
      'win/novice/knightBishop': { success: 11, requested: 16 },
      'win/novice/pawn': { success: 12, requested: 18 },
      'win/novice/rookPawn': { success: 6, requested: 9 },
      'win/novice/rookPieces': { success: 6, requested: 9 },
      'win/pro/bishop': { success: 7, requested: 10 },
      'win/pro/knight': { success: 3, requested: 4 },
      'win/pro/knightBishop': { success: 11, requested: 16 },
      'win/pro/pawn': { success: 7, requested: 10 },
      'win/pro/queen': { success: 13, requested: 19 },
      'win/pro/rookPieces': { success: 14, requested: 21 },
      'win/master/bishop': { success: 14, requested: 21 },
      'win/master/knight': { success: 10, requested: 15 },
      'win/master/knightBishop': { success: 4, requested: 6 },
      'win/master/pawn': { success: 9, requested: 13 },
      'win/master/queen': { success: 9, requested: 13 },
      'win/master/rookPawn': { success: 6, requested: 9 },
      'win/master/rookPieces': { success: 4, requested: 6 },
      'draw/novice/bishop': { success: 4, requested: 6 },
      'draw/novice/knight': { success: 4, requested: 6 },
      'draw/novice/knightBishop': { success: 4, requested: 6 },
      'draw/novice/pawn': { success: 5, requested: 7 },
      'draw/novice/queen': { success: 14, requested: 21 },
      'draw/novice/rookPawn': { success: 8, requested: 12 },
      'draw/novice/rookPieces': { success: 10, requested: 15 },
      'draw/pro/bishop': { success: 7, requested: 10 },
      'draw/pro/knight': { success: 7, requested: 10 },
      'draw/pro/knightBishop': { success: 7, requested: 10 },
      'draw/pro/pawn': { success: 2, requested: 3 },
      'draw/pro/queen': { success: 6, requested: 9 },
      'draw/pro/rookPawn': { success: 11, requested: 16 },
      'draw/pro/rookPieces': { success: 9, requested: 13 },
      'draw/master/bishop': { success: 8, requested: 12 },
      'draw/master/knight': { success: 14, requested: 21 },
      'draw/master/knightBishop': { success: 12, requested: 18 },
      'draw/master/pawn': { success: 4, requested: 6 },
      'draw/master/queen': { success: 4, requested: 6 },
      'draw/master/rookPawn': { success: 1, requested: 1 },
      'draw/master/rookPieces': { success: 11, requested: 16 },
    },
  },
  practical: {
    stats: {
      'win/novice/extraPawn': { success: 2, requested: 3 },
      'win/novice/materialEquality': { success: 3, requested: 4 },
      'win/novice/bishop': { success: 10, requested: 15 },
      'win/novice/knight': { success: 18, requested: 27 },
      'win/novice/pawn': { success: 1, requested: 1 },
      'win/novice/queen': { success: 7, requested: 10 },
      'win/novice/rook': { success: 15, requested: 22 },
      'win/novice/exchange': { success: 8, requested: 12 },
      'win/novice/knightBishop': { success: 12, requested: 18 },
      'win/pro/extraPawn': { success: 9, requested: 13 },
      'win/pro/materialEquality': { success: 4, requested: 6 },
      'win/pro/bishop': { success: 12, requested: 18 },
      'win/pro/knight': { success: 19, requested: 28 },
      'win/pro/pawn': { success: 12, requested: 18 },
      'win/pro/queen': { success: 2, requested: 3 },
      'win/pro/rook': { success: 3, requested: 4 },
      'win/pro/exchange': { success: 5, requested: 7 },
      'win/pro/knightBishop': { success: 11, requested: 16 },
      'win/master/extraPawn': { success: 9, requested: 13 },
      'win/master/materialEquality': { success: 1, requested: 1 },
      'win/master/bishop': { success: 4, requested: 6 },
      'win/master/knight': { success: 11, requested: 16 },
      'win/master/pawn': { success: 10, requested: 15 },
      'win/master/queen': { success: 0, requested: 0 },
      'win/master/rook': { success: 15, requested: 22 },
      'win/master/exchange': { success: 10, requested: 15 },
      'win/master/knightBishop': { success: 16, requested: 24 },
    },
  },
}

export const EXAMPLE_HALL_OF_FAME_DATA: LeaderboardApiResponse = {
  tornadoLeaderboard: {
    bullet: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 42, days_old: 1, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 27, days_old: 5, subscriptionTier: 'Queen' },
      { rank: 3, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', highScore: 14, days_old: 6, subscriptionTier: 'Knight' },
      { rank: 4, username: 'TheMatist', lichess_id: 'the_matist', highScore: 1, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    blitz: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 62, days_old: 4, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 14, days_old: 6, subscriptionTier: 'Queen' },
    ],
    rapid: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 77, days_old: 1, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 25, days_old: 3, subscriptionTier: 'Queen' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', highScore: 24, days_old: 1, subscriptionTier: 'Bishop' },
      { rank: 4, username: 'SlowThinker', lichess_id: 'slow_thinker', highScore: 13, days_old: 3, subscriptionTier: 'Rook' },
    ],
    classic: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', highScore: 29, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', highScore: 16, days_old: 5, subscriptionTier: 'Rook' },
    ],
  },
  finishHimLeaderboard: {
    pawn: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', best_time: 59, days_old: 0, puzzle_id: 'p1', subscriptionTier: 'Knight' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', best_time: 53, days_old: 0, puzzle_id: 'p2', subscriptionTier: 'Bishop' },
    ],
    knight: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', best_time: 123, days_old: 0, puzzle_id: 'k1', subscriptionTier: 'Pawn' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', best_time: 79, days_old: 0, puzzle_id: 'k2', subscriptionTier: 'Queen' },
    ],
    bishop: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', best_time: 140, days_old: 0, puzzle_id: 'b1', subscriptionTier: 'Rook' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', best_time: 120, days_old: 0, puzzle_id: 'b2', subscriptionTier: 'King' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', best_time: 54, days_old: 0, puzzle_id: 'b3', subscriptionTier: 'Pawn' },
    ],
    rookPawn: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', best_time: 30, days_old: 0, puzzle_id: 'rp1', subscriptionTier: 'King' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', best_time: 15, days_old: 0, puzzle_id: 'rp2', subscriptionTier: 'Bishop' },
    ],
    queen: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', best_time: 22, days_old: 0, puzzle_id: 'q1', subscriptionTier: 'Pawn' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', best_time: 75, days_old: 0, puzzle_id: 'q2', subscriptionTier: 'Queen' },
      { rank: 3, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', best_time: 42, days_old: 0, puzzle_id: 'q3', subscriptionTier: 'Knight' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', best_time: 33, days_old: 0, puzzle_id: 'q4', subscriptionTier: 'King' },
    ],
    knightBishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', best_time: 139, days_old: 0, puzzle_id: 'kb1', subscriptionTier: 'Knight' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', best_time: 82, days_old: 0, puzzle_id: 'kb2', subscriptionTier: 'Queen' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', best_time: 45, days_old: 0, puzzle_id: 'kb3', subscriptionTier: 'Rook' },
    ],
    rookPieces: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', best_time: 174, days_old: 0, puzzle_id: 'r1', subscriptionTier: 'Bishop' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', best_time: 114, days_old: 0, puzzle_id: 'r2', subscriptionTier: 'Knight' },
    ],
    queenPieces: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', best_time: 112, days_old: 0, puzzle_id: 'qp1', subscriptionTier: 'King' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', best_time: 82, days_old: 0, puzzle_id: 'qp2', subscriptionTier: 'Pawn' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', best_time: 74, days_old: 0, puzzle_id: 'qp3', subscriptionTier: 'Rook' },
      { rank: 4, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', best_time: 37, days_old: 0, puzzle_id: 'qp4', subscriptionTier: 'Knight' },
    ],
    expert: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', best_time: 24, days_old: 0, puzzle_id: 'e1', subscriptionTier: 'Rook' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', best_time: 16, days_old: 0, puzzle_id: 'e2', subscriptionTier: 'Bishop' },
      { rank: 3, username: 'BlitzDemon', lichess_id: 'blitz_demon', best_time: 15, days_old: 0, puzzle_id: 'e3', subscriptionTier: 'Queen' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', best_time: 29, days_old: 0, puzzle_id: 'e4', subscriptionTier: 'Pawn' },
      { rank: 5, username: 'VALID_ALL', lichess_id: 'valid_all', best_time: 21, days_old: 0, puzzle_id: 'e5', subscriptionTier: 'King' },
    ],
  },
  theoryLeaderboard: {
    bishop: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 118, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 92, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 78, days_old: 0, subscriptionTier: 'King' },
    ],
    knight: [
      { rank: 1, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 288, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 49, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 47, days_old: 0, subscriptionTier: 'King' },
    ],
    knightBishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 198, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', score: 122, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 98, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', score: 93, days_old: 0, subscriptionTier: 'King' },
      { rank: 5, username: 'TheMatist', lichess_id: 'the_matist', score: 45, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    pawn: [
      { rank: 1, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 125, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 122, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 103, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', score: 52, days_old: 0, subscriptionTier: 'King' },
    ],
    queen: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 109, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 91, days_old: 0, subscriptionTier: 'King' },
    ],
    rookPawn: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 107, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 83, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 80, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', score: 56, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 5, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 40, days_old: 0, subscriptionTier: 'Queen' },
    ],
    rookPieces: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 164, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 130, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 79, days_old: 0, subscriptionTier: 'King' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', score: 70, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 5, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 60, days_old: 0, subscriptionTier: 'Knight' },
    ],
  },
  practicalLeaderboard: {
    extraPawn: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 257, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 147, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', score: 77, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    materialEquality: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 26, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 5, days_old: 0, subscriptionTier: 'King' },
    ],
    bishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 181, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 135, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 85, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 57, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 5, username: 'TheMatist', lichess_id: 'the_matist', score: 47, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    knight: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 215, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 74, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 25, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 22, days_old: 0, subscriptionTier: 'Queen' },
    ],
    pawn: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 162, days_old: 0, subscriptionTier: 'Pawn' },
    ],
    queen: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 88, days_old: 0, subscriptionTier: 'King' },
    ],
    rook: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 163, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', score: 46, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 3, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 19, days_old: 0, subscriptionTier: 'Queen' },
    ],
    exchange: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 149, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 90, days_old: 0, subscriptionTier: 'King' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', score: 86, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 19, days_old: 0, subscriptionTier: 'Queen' },
    ],
    knightBishop: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 183, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 128, days_old: 0, subscriptionTier: 'King' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 108, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 59, days_old: 0, subscriptionTier: 'Queen' },
    ],
  },
  overallSkillLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', subscriptionTier: 'King', total_solved: 4000, total_score: 7834, solved_by_mode: { tornado: 6023, finishHim: 593, theory: 440, 'practical-chess': 778, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', subscriptionTier: 'Pawn', total_solved: 887, total_score: 1814, solved_by_mode: { tornado: 480, finishHim: 490, theory: 351, 'practical-chess': 493, tacticalTrainer: 0 } },
    { lichess_id: 'slow_thinker', username: 'SlowThinker', subscriptionTier: 'Rook', total_solved: 924, total_score: 1802, solved_by_mode: { tornado: 472, finishHim: 507, theory: 417, 'practical-chess': 406, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', subscriptionTier: 'Bishop', total_solved: 893, total_score: 1792, solved_by_mode: { tornado: 419, finishHim: 546, theory: 434, 'practical-chess': 393, tacticalTrainer: 0 } },
    { lichess_id: 'unbalanced_one', username: 'UnbalancedOne', subscriptionTier: 'Knight', total_solved: 789, total_score: 1562, solved_by_mode: { tornado: 257, finishHim: 391, theory: 512, 'practical-chess': 402, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', subscriptionTier: 'Queen', total_solved: 764, total_score: 1470, solved_by_mode: { tornado: 363, finishHim: 386, theory: 545, 'practical-chess': 176, tacticalTrainer: 0 } },
  ],
  skillStreakLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', current_streak: 35, subscriptionTier: 'King', total_solved: 16854, total_score: 32334, solved_by_mode: { tornado: 24974, finishHim: 2637, theory: 2146, 'practical-chess': 2577, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', current_streak: 7, subscriptionTier: 'Bishop', total_solved: 872, total_score: 1759, solved_by_mode: { tornado: 419, finishHim: 513, theory: 434, 'practical-chess': 393, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', current_streak: 2, subscriptionTier: 'Pawn', total_solved: 277, total_score: 534, solved_by_mode: { tornado: 169, finishHim: 131, theory: 56, 'practical-chess': 178, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', current_streak: 1, subscriptionTier: 'Queen', total_solved: 126, total_score: 298, solved_by_mode: { tornado: 39, finishHim: 112, theory: 125, 'practical-chess': 22, tacticalTrainer: 0 } },
  ],
  skillStreakMegaLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', current_streak: 35, subscriptionTier: 'King', total_solved: 16854, total_score: 32334, solved_by_mode: { tornado: 24974, finishHim: 2637, theory: 2146, 'practical-chess': 2577, tacticalTrainer: 0 } },
  ],
  topTodayLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', subscriptionTier: 'King', total_solved: 534, total_score: 720, solved_by_mode: { tornado: 509, finishHim: 37, theory: 41, 'practical-chess': 133, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', subscriptionTier: 'Pawn', total_solved: 168, total_score: 285, solved_by_mode: { tornado: 59, finishHim: 77, theory: 56, 'practical-chess': 93, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', subscriptionTier: 'Bishop', total_solved: 137, total_score: 230, solved_by_mode: { tornado: 11, finishHim: 72, theory: 70, 'practical-chess': 77, tacticalTrainer: 0 } },
    { lichess_id: 'unbalanced_one', username: 'UnbalancedOne', subscriptionTier: 'Knight', total_solved: 85, total_score: 159, solved_by_mode: { tornado: 33, finishHim: 0, theory: 52, 'practical-chess': 74, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', subscriptionTier: 'Queen', total_solved: 71, total_score: 108, solved_by_mode: { tornado: 68, finishHim: 0, theory: 40, 'practical-chess': 0, tacticalTrainer: 0 } },
    { lichess_id: 'slow_thinker', username: 'SlowThinker', subscriptionTier: 'Rook', total_solved: 47, total_score: 53, solved_by_mode: { tornado: 53, finishHim: 0, theory: 0, 'practical-chess': 0, tacticalTrainer: 0 } },
  ],
}
