import type {
  LeaderboardApiResponse,
  PersonalActivityStatsResponse,
  UserProfileStatsDto,
  UserSessionProfile,
} from '../types/api.types'

export const EXAMPLE_USER_PROFILE: UserSessionProfile = {
  id: 'valid_all',
  username: 'VALID_ALL',
  perfs: {
    blitz: {
      rating: 1958,
      prog: 0,
      games: 0,
    },
  },
  createdAt: 1770792222695,
  profile: {},
  FunCoins: 100,
  subscriptionTier: 'King',
  TierExpire: null,
  tornadoHighScores: {
    bullet: 58,
    blitz: 26,
    rapid: 50,
    classic: 22,
  },
  validatedAt: 1770796114301,
  today_activity: {
    puzzles_solved_today: {
      tornado: 307,
      advantage: 57,
      theory: 47,
      'practical-chess': 0,
      tacticalTrainer: 0,
      total: 411,
    },
  },
  endgame_skill: 1500,
}

export const EXAMPLE_ACTIVITY_STATS: PersonalActivityStatsResponse = {
  daily: {
    tornado: { puzzles_requested: 307, puzzles_solved: 307 },
    advantage: { puzzles_requested: 60, puzzles_solved: 57 },
    theory: { puzzles_requested: 50, puzzles_solved: 47 },
    'practical-chess': { puzzles_requested: 0, puzzles_solved: 0 },
  },
  weekly: {
    tornado: { puzzles_requested: 2999, puzzles_solved: 2973 },
    advantage: { puzzles_requested: 270, puzzles_solved: 228 },
    theory: { puzzles_requested: 327, puzzles_solved: 294 },
    'practical-chess': { puzzles_requested: 0, puzzles_solved: 0 },
  },
  monthly: {
    tornado: { puzzles_requested: 11931, puzzles_solved: 11821 },
    advantage: { puzzles_requested: 1210, puzzles_solved: 1047 },
    theory: { puzzles_requested: 1216, puzzles_solved: 1067 },
    'practical-chess': { puzzles_requested: 0, puzzles_solved: 0 },
  },
}

export const EXAMPLE_DETAILED_STATS: UserProfileStatsDto = {
  tornado: {
    highScores: { bullet: 58, blitz: 26, rapid: 50, classic: 22 },
    modes: {
      bullet: [
        { theme: 'capturingDefender', success: 44, requested: 48, rating: 2413 },
        { theme: 'trappedPiece', success: 16, requested: 17, rating: 2342 },
        { theme: 'fork', success: 31, requested: 34, rating: 2335 },
        { theme: 'skewer', success: 45, requested: 49, rating: 2335 },
        { theme: 'pin', success: 42, requested: 46, rating: 2329 },
        { theme: 'discoveredAttack', success: 13, requested: 14, rating: 2254 },
        { theme: 'doubleCheck', success: 1, requested: 1, rating: 2182 },
        { theme: 'deflection', success: 7, requested: 7, rating: 2045 },
        { theme: 'interference', success: 22, requested: 24, rating: 2031 },
        { theme: 'xRayAttack', success: 39, requested: 42, rating: 1902 },
        { theme: 'backRankMate', success: 39, requested: 42, rating: 1877 },
        { theme: 'quietMove', success: 24, requested: 26, rating: 1696 },
        { theme: 'clearance', success: 36, requested: 39, rating: 1695 },
        { theme: 'attraction', success: 3, requested: 3, rating: 1661 },
        { theme: 'promotion', success: 18, requested: 19, rating: 1627 },
      ],
      blitz: [
        { theme: 'capturingDefender', success: 6, requested: 6, rating: 2493 },
        { theme: 'clearance', success: 34, requested: 37, rating: 2466 },
        { theme: 'promotion', success: 20, requested: 21, rating: 2453 },
        { theme: 'trappedPiece', success: 39, requested: 42, rating: 2453 },
        { theme: 'backRankMate', success: 18, requested: 19, rating: 2197 },
        { theme: 'quietMove', success: 22, requested: 24, rating: 2147 },
        { theme: 'xRayAttack', success: 0, requested: 0, rating: 1970 },
        { theme: 'doubleCheck', success: 6, requested: 6, rating: 1957 },
        { theme: 'fork', success: 10, requested: 10, rating: 1895 },
        { theme: 'pin', success: 8, requested: 8, rating: 1848 },
        { theme: 'attraction', success: 49, requested: 53, rating: 1844 },
        { theme: 'skewer', success: 16, requested: 17, rating: 1727 },
        { theme: 'deflection', success: 22, requested: 24, rating: 1713 },
        { theme: 'discoveredAttack', success: 31, requested: 34, rating: 1681 },
        { theme: 'interference', success: 47, requested: 51, rating: 1540 },
      ],
      rapid: [
        { theme: 'xRayAttack', success: 15, requested: 16, rating: 2467 },
        { theme: 'clearance', success: 44, requested: 48, rating: 2406 },
        { theme: 'capturingDefender', success: 32, requested: 35, rating: 2394 },
        { theme: 'attraction', success: 22, requested: 24, rating: 2185 },
        { theme: 'trappedPiece', success: 15, requested: 16, rating: 2153 },
        { theme: 'fork', success: 41, requested: 45, rating: 2072 },
        { theme: 'backRankMate', success: 19, requested: 20, rating: 1912 },
        { theme: 'deflection', success: 45, requested: 49, rating: 1825 },
        { theme: 'pin', success: 11, requested: 12, rating: 1712 },
        { theme: 'skewer', success: 49, requested: 53, rating: 1697 },
        { theme: 'promotion', success: 17, requested: 18, rating: 1685 },
        { theme: 'discoveredAttack', success: 37, requested: 40, rating: 1611 },
        { theme: 'quietMove', success: 30, requested: 32, rating: 1567 },
        { theme: 'doubleCheck', success: 49, requested: 53, rating: 1530 },
        { theme: 'interference', success: 22, requested: 24, rating: 1523 },
      ],
      classic: [
        { theme: 'clearance', success: 11, requested: 12, rating: 2454 },
        { theme: 'deflection', success: 39, requested: 42, rating: 2418 },
        { theme: 'pin', success: 20, requested: 21, rating: 2395 },
        { theme: 'discoveredAttack', success: 12, requested: 13, rating: 2335 },
        { theme: 'backRankMate', success: 47, requested: 51, rating: 2143 },
        { theme: 'trappedPiece', success: 38, requested: 41, rating: 2082 },
        { theme: 'interference', success: 12, requested: 13, rating: 2038 },
        { theme: 'skewer', success: 21, requested: 23, rating: 2004 },
        { theme: 'doubleCheck', success: 14, requested: 15, rating: 1947 },
        { theme: 'fork', success: 12, requested: 13, rating: 1903 },
        { theme: 'xRayAttack', success: 47, requested: 51, rating: 1902 },
        { theme: 'quietMove', success: 34, requested: 37, rating: 1900 },
        { theme: 'capturingDefender', success: 39, requested: 42, rating: 1645 },
        { theme: 'promotion', success: 5, requested: 5, rating: 1572 },
        { theme: 'attraction', success: 41, requested: 45, rating: 1541 },
      ],
    },
  },
  advantage: {
    themes: [
      { theme: 'pawn', rating: 1664, success: 34, requested: 45 },
      { theme: 'queenPieces', rating: 1635, success: 18, requested: 23 },
      { theme: 'queen', rating: 1596, success: 18, requested: 23 },
      { theme: 'rookPawn', rating: 1571, success: 34, requested: 45 },
      { theme: 'expert', rating: 1549, success: 40, requested: 53 },
      { theme: 'knight', rating: 1459, success: 34, requested: 44 },
      { theme: 'rookPieces', rating: 1393, success: 38, requested: 49 },
      { theme: 'bishop', rating: 1380, success: 50, requested: 66 },
      { theme: 'knightBishop', rating: 1304, success: 46, requested: 60 },
    ],
    stats: {
      'win/Novice/pawn': { requested: 3, success: 3 },
      'win/Novice/knight': { requested: 5, success: 4 },
      'win/Novice/bishop': { requested: 11, success: 9 },
      'win/Novice/rookPawn': { requested: 9, success: 7 },
      'win/Novice/queen': { requested: 2, success: 2 },
      'win/Novice/knightBishop': { requested: 10, success: 8 },
      'win/Novice/rookPieces': { requested: 11, success: 9 },
      'win/Novice/queenPieces': { requested: 1, success: 1 },
      'win/Novice/expert': { requested: 7, success: 6 },
      'win/Pro/pawn': { requested: 10, success: 8 },
      'win/Pro/knight': { requested: 11, success: 9 },
      'win/Pro/bishop': { requested: 9, success: 7 },
      'win/Pro/rookPawn': { requested: 2, success: 2 },
      'win/Pro/queen': { requested: 5, success: 4 },
      'win/Pro/knightBishop': { requested: 7, success: 6 },
      'win/Pro/rookPieces': { requested: 10, success: 8 },
      'win/Pro/queenPieces': { requested: 6, success: 5 },
      'win/Pro/expert': { requested: 1, success: 1 },
      'win/Master/pawn': { requested: 0, success: 0 },
      'win/Master/knight': { requested: 7, success: 6 },
      'win/Master/bishop': { requested: 10, success: 8 },
      'win/Master/rookPawn': { requested: 1, success: 1 },
      'win/Master/queen': { requested: 0, success: 0 },
      'win/Master/knightBishop': { requested: 3, success: 3 },
      'win/Master/rookPieces': { requested: 5, success: 4 },
      'win/Master/queenPieces': { requested: 0, success: 0 },
      'win/Master/expert': { requested: 9, success: 7 },
      'win/standard/pawn': { success: 23, requested: 32 },
      'win/standard/knight': { success: 15, requested: 21 },
      'win/standard/bishop': { success: 26, requested: 36 },
      'win/standard/rookPawn': { success: 24, requested: 33 },
      'win/standard/queen': { success: 12, requested: 16 },
      'win/standard/knightBishop': { success: 29, requested: 40 },
      'win/standard/rookPieces': { success: 17, requested: 23 },
      'win/standard/queenPieces': { success: 12, requested: 16 },
      'win/standard/expert': { success: 26, requested: 36 },
    },
  },
  theory: {
    stats: {
      'win/Novice/bishop': { requested: 6, success: 4 },
      'win/Novice/knight': { requested: 12, success: 8 },
      'win/Novice/knightBishop': { requested: 1, success: 1 },
      'win/Novice/pawn': { requested: 4, success: 3 },
      'win/Novice/queen': { requested: 21, success: 14 },
      'win/Novice/rookPawn': { requested: 0, success: 0 },
      'win/Novice/rookPieces': { requested: 15, success: 10 },
      'win/Pro/bishop': { requested: 18, success: 12 },
      'win/Pro/knight': { requested: 4, success: 3 },
      'win/Pro/knightBishop': { requested: 21, success: 14 },
      'win/Pro/pawn': { requested: 0, success: 0 },
      'win/Pro/queen': { requested: 0, success: 0 },
      'win/Pro/rookPawn': { requested: 3, success: 2 },
      'win/Pro/rookPieces': { requested: 6, success: 4 },
      'win/Master/bishop': { requested: 21, success: 14 },
      'win/Master/knight': { requested: 6, success: 4 },
      'win/Master/knightBishop': { requested: 10, success: 7 },
      'win/Master/pawn': { requested: 19, success: 13 },
      'win/Master/queen': { requested: 21, success: 14 },
      'win/Master/rookPawn': { requested: 4, success: 3 },
      'win/Master/rookPieces': { requested: 12, success: 8 },
      'draw/Novice/bishop': { requested: 1, success: 1 },
      'draw/Novice/knight': { requested: 12, success: 8 },
      'draw/Novice/knightBishop': { requested: 9, success: 6 },
      'draw/Novice/pawn': { requested: 15, success: 10 },
      'draw/Novice/queen': { requested: 1, success: 1 },
      'draw/Novice/rookPawn': { requested: 3, success: 2 },
      'draw/Novice/rookPieces': { requested: 18, success: 12 },
      'draw/Pro/bishop': { requested: 13, success: 9 },
      'draw/Pro/knight': { requested: 10, success: 7 },
      'draw/Pro/knightBishop': { requested: 7, success: 5 },
      'draw/Pro/pawn': { requested: 13, success: 9 },
      'draw/Pro/queen': { requested: 15, success: 10 },
      'draw/Pro/rookPawn': { requested: 15, success: 10 },
      'draw/Pro/rookPieces': { requested: 19, success: 13 },
      'draw/Master/bishop': { requested: 19, success: 13 },
      'draw/Master/knight': { requested: 13, success: 9 },
      'draw/Master/knightBishop': { requested: 19, success: 13 },
      'draw/Master/pawn': { requested: 21, success: 14 },
      'draw/Master/queen': { requested: 15, success: 10 },
      'draw/Master/rookPawn': { requested: 1, success: 1 },
      'draw/Master/rookPieces': { requested: 0, success: 0 },
    },
  },
  practical: {
    stats: {
      'win/Novice/extraPawn': { success: 8, requested: 12 },
      'win/Novice/materialEquality': { success: 8, requested: 12 },
      'win/Novice/bishop': { success: 7, requested: 10 },
      'win/Novice/knight': { success: 19, requested: 28 },
      'win/Novice/pawn': { success: 13, requested: 19 },
      'win/Novice/queen': { success: 12, requested: 18 },
      'win/Novice/rook': { success: 11, requested: 16 },
      'win/Novice/exchange': { success: 8, requested: 12 },
      'win/Novice/knightBishop': { success: 16, requested: 24 },
      'win/Pro/extraPawn': { success: 0, requested: 0 },
      'win/Pro/materialEquality': { success: 10, requested: 15 },
      'win/Pro/bishop': { success: 0, requested: 0 },
      'win/Pro/knight': { success: 2, requested: 3 },
      'win/Pro/pawn': { success: 18, requested: 27 },
      'win/Pro/queen': { success: 5, requested: 7 },
      'win/Pro/rook': { success: 1, requested: 1 },
      'win/Pro/exchange': { success: 9, requested: 13 },
      'win/Pro/knightBishop': { success: 11, requested: 16 },
      'win/Master/extraPawn': { success: 17, requested: 25 },
      'win/Master/materialEquality': { success: 11, requested: 16 },
      'win/Master/bishop': { success: 8, requested: 12 },
      'win/Master/knight': { success: 16, requested: 24 },
      'win/Master/pawn': { success: 16, requested: 24 },
      'win/Master/queen': { success: 15, requested: 22 },
      'win/Master/rook': { success: 1, requested: 1 },
      'win/Master/exchange': { success: 16, requested: 24 },
      'win/Master/knightBishop': { success: 18, requested: 27 },
    },
  },
}

export const EXAMPLE_HALL_OF_FAME_DATA: LeaderboardApiResponse = {
  tornadoLeaderboard: {
    bullet: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 42, days_old: 1, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 27, days_old: 5, subscriptionTier: 'Queen' },
      { rank: 3, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', highScore: 14, days_old: 6, subscriptionTier: 'Knight' },
      { rank: 4, username: 'TheMatist', lichess_id: 'the_matist', highScore: 1, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    blitz: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 62, days_old: 4, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 14, days_old: 6, subscriptionTier: 'Queen' },
    ],
    rapid: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', highScore: 77, days_old: 1, subscriptionTier: 'King' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', highScore: 25, days_old: 3, subscriptionTier: 'Queen' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', highScore: 24, days_old: 1, subscriptionTier: 'Bishop' },
      { rank: 4, username: 'SlowThinker', lichess_id: 'slow_thinker', highScore: 13, days_old: 3, subscriptionTier: 'Rook' },
    ],
    classic: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', highScore: 29, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', highScore: 16, days_old: 5, subscriptionTier: 'Rook' },
    ],
  },
  advantageLeaderboard: {
    pawn: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 59, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', score: 53, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    knight: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 123, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 79, days_old: 0, subscriptionTier: 'Queen' },
    ],
    bishop: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 140, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 120, days_old: 0, subscriptionTier: 'King' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 54, days_old: 0, subscriptionTier: 'Pawn' },
    ],
    rookPawn: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 307, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', score: 153, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    queen: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 202, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 75, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 3, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 42, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', score: 33, days_old: 0, subscriptionTier: 'King' },
    ],
    knightBishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 139, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 82, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 45, days_old: 0, subscriptionTier: 'Rook' },
    ],
    rookPieces: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 174, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 114, days_old: 0, subscriptionTier: 'Knight' },
    ],
    queenPieces: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 112, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', score: 82, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 74, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 37, days_old: 0, subscriptionTier: 'Knight' },
    ],
    expert: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 248, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'TheMatist', lichess_id: 'the_matist', score: 166, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 3, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 150, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', score: 29, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 5, username: 'VALID_ALL', lichess_id: 'valid_all', score: 21, days_old: 0, subscriptionTier: 'King' },
    ],
  },
  theoryLeaderboard: {
    bishop: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 118, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 92, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 78, days_old: 0, subscriptionTier: 'King' },
    ],
    knight: [
      { rank: 1, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 288, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 49, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 47, days_old: 0, subscriptionTier: 'King' },
    ],
    knightBishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 198, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', score: 122, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 98, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', score: 93, days_old: 0, subscriptionTier: 'King' },
      { rank: 5, username: 'TheMatist', lichess_id: 'the_matist', score: 45, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    pawn: [
      { rank: 1, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 125, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 122, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 103, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'VALID_ALL', lichess_id: 'valid_all', score: 52, days_old: 0, subscriptionTier: 'King' },
    ],
    queen: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 109, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 91, days_old: 0, subscriptionTier: 'King' },
    ],
    rookPawn: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 107, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 83, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 80, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', score: 56, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 5, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 40, days_old: 0, subscriptionTier: 'Queen' },
    ],
    rookPieces: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 164, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 130, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 3, username: 'VALID_ALL', lichess_id: 'valid_all', score: 79, days_old: 0, subscriptionTier: 'King' },
      { rank: 4, username: 'TacticMaster', lichess_id: 'tactic_master', score: 70, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 5, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 60, days_old: 0, subscriptionTier: 'Knight' },
    ],
  },
  practicalLeaderboard: {
    extraPawn: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 257, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 147, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', score: 77, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    materialEquality: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 26, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 5, days_old: 0, subscriptionTier: 'King' },
    ],
    bishop: [
      { rank: 1, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 181, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 2, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 135, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 85, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 57, days_old: 0, subscriptionTier: 'Queen' },
      { rank: 5, username: 'TheMatist', lichess_id: 'the_matist', score: 47, days_old: 0, subscriptionTier: 'Bishop' },
    ],
    knight: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 215, days_old: 0, subscriptionTier: 'King' },
      { rank: 2, username: 'UnbalancedOne', lichess_id: 'unbalanced_one', score: 74, days_old: 0, subscriptionTier: 'Knight' },
      { rank: 3, username: 'TacticMaster', lichess_id: 'tactic_master', score: 25, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 22, days_old: 0, subscriptionTier: 'Queen' },
    ],
    pawn: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 162, days_old: 0, subscriptionTier: 'Pawn' },
    ],
    queen: [
      { rank: 1, username: 'VALID_ALL', lichess_id: 'valid_all', score: 88, days_old: 0, subscriptionTier: 'King' },
    ],
    rook: [
      { rank: 1, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 163, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 2, username: 'TacticMaster', lichess_id: 'tactic_master', score: 46, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 3, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 19, days_old: 0, subscriptionTier: 'Queen' },
    ],
    exchange: [
      { rank: 1, username: 'TacticMaster', lichess_id: 'tactic_master', score: 149, days_old: 0, subscriptionTier: 'Pawn' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 90, days_old: 0, subscriptionTier: 'King' },
      { rank: 3, username: 'TheMatist', lichess_id: 'the_matist', score: 86, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 19, days_old: 0, subscriptionTier: 'Queen' },
    ],
    knightBishop: [
      { rank: 1, username: 'TheMatist', lichess_id: 'the_matist', score: 183, days_old: 0, subscriptionTier: 'Bishop' },
      { rank: 2, username: 'VALID_ALL', lichess_id: 'valid_all', score: 128, days_old: 0, subscriptionTier: 'King' },
      { rank: 3, username: 'SlowThinker', lichess_id: 'slow_thinker', score: 108, days_old: 0, subscriptionTier: 'Rook' },
      { rank: 4, username: 'BlitzDemon', lichess_id: 'blitz_demon', score: 59, days_old: 0, subscriptionTier: 'Queen' },
    ],
  },
  overallSkillLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', subscriptionTier: 'King', total_solved: 4000, total_score: 7834, solved_by_mode: { tornado: 6023, advantage: 593, theory: 440, 'practical-chess': 778, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', subscriptionTier: 'Pawn', total_solved: 887, total_score: 1814, solved_by_mode: { tornado: 480, advantage: 490, theory: 351, 'practical-chess': 493, tacticalTrainer: 0 } },
    { lichess_id: 'slow_thinker', username: 'SlowThinker', subscriptionTier: 'Rook', total_solved: 924, total_score: 1802, solved_by_mode: { tornado: 472, advantage: 507, theory: 417, 'practical-chess': 406, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', subscriptionTier: 'Bishop', total_solved: 893, total_score: 1792, solved_by_mode: { tornado: 419, advantage: 546, theory: 434, 'practical-chess': 393, tacticalTrainer: 0 } },
    { lichess_id: 'unbalanced_one', username: 'UnbalancedOne', subscriptionTier: 'Knight', total_solved: 789, total_score: 1562, solved_by_mode: { tornado: 257, advantage: 391, theory: 512, 'practical-chess': 402, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', subscriptionTier: 'Queen', total_solved: 764, total_score: 1470, solved_by_mode: { tornado: 363, advantage: 386, theory: 545, 'practical-chess': 176, tacticalTrainer: 0 } },
  ],
  skillStreakLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', current_streak: 35, subscriptionTier: 'King', total_solved: 16854, total_score: 32334, solved_by_mode: { tornado: 24974, advantage: 2637, theory: 2146, 'practical-chess': 2577, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', current_streak: 7, subscriptionTier: 'Bishop', total_solved: 872, total_score: 1759, solved_by_mode: { tornado: 419, advantage: 513, theory: 434, 'practical-chess': 393, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', current_streak: 2, subscriptionTier: 'Pawn', total_solved: 277, total_score: 534, solved_by_mode: { tornado: 169, advantage: 131, theory: 56, 'practical-chess': 178, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', current_streak: 1, subscriptionTier: 'Queen', total_solved: 126, total_score: 298, solved_by_mode: { tornado: 39, advantage: 112, theory: 125, 'practical-chess': 22, tacticalTrainer: 0 } },
  ],
  skillStreakMegaLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', current_streak: 35, subscriptionTier: 'King', total_solved: 16854, total_score: 32334, solved_by_mode: { tornado: 24974, advantage: 2637, theory: 2146, 'practical-chess': 2577, tacticalTrainer: 0 } },
  ],
  topTodayLeaderboard: [
    { lichess_id: 'valid_all', username: 'VALID_ALL', subscriptionTier: 'King', total_solved: 534, total_score: 720, solved_by_mode: { tornado: 509, advantage: 37, theory: 41, 'practical-chess': 133, tacticalTrainer: 0 } },
    { lichess_id: 'tactic_master', username: 'TacticMaster', subscriptionTier: 'Pawn', total_solved: 168, total_score: 285, solved_by_mode: { tornado: 59, advantage: 77, theory: 56, 'practical-chess': 93, tacticalTrainer: 0 } },
    { lichess_id: 'the_matist', username: 'TheMatist', subscriptionTier: 'Bishop', total_solved: 137, total_score: 230, solved_by_mode: { tornado: 11, advantage: 72, theory: 70, 'practical-chess': 77, tacticalTrainer: 0 } },
    { lichess_id: 'unbalanced_one', username: 'UnbalancedOne', subscriptionTier: 'Knight', total_solved: 85, total_score: 159, solved_by_mode: { tornado: 33, advantage: 0, theory: 52, 'practical-chess': 74, tacticalTrainer: 0 } },
    { lichess_id: 'blitz_demon', username: 'BlitzDemon', subscriptionTier: 'Queen', total_solved: 71, total_score: 108, solved_by_mode: { tornado: 68, advantage: 0, theory: 40, 'practical-chess': 0, tacticalTrainer: 0 } },
    { lichess_id: 'slow_thinker', username: 'SlowThinker', subscriptionTier: 'Rook', total_solved: 47, total_score: 53, solved_by_mode: { tornado: 53, advantage: 0, theory: 0, 'practical-chess': 0, tacticalTrainer: 0 } },
  ],
}
