// src/utils/theme-mapper.ts

export const THEME_KEY_MAP: Record<string, string> = {
  // From FinishHim/Tower
  mix: 'mix',
  rook_and_minor_vs_rook: 'rookAndMinorVsRook',
  rook_endgame: 'rookEndgame',
  pawn_endgame: 'pawnEndgame',
  queens_vs_rooks: 'queensVsRooks',
  knight_endgame: 'knightEndgame',
  bishop_endgame: 'bishopEndgame',
  rooks_vs_minors: 'rooksVsMinors',
  opposite_color_bishops: 'oppositeColorBishops',
  two_rooks_endgame: 'twoRooksEndgame',
  queens_vs_minors: 'queensVsMinors',
  queen_endgame: 'queenEndgame',
  knights_vs_bishops: 'knightsVsBishops',
  bishops_vs_knights: 'bishopsVsKnights',
  minors_vs_rooks: 'minorsVsRooks',
  vs_queen_disadvantage: 'vsQueenDisadvantage',

  // From AnalyticsDisplay
  'Heavy Pieces Endgame': 'heavyPiecesEndgame',
  'Minor Pieces Endgame': 'minorPiecesEndgame',
  'Double Rooks Endgame': 'twoRooksEndgame',
  'Bishop vs Knight': 'bishopVsKnight',
  'Knight vs Bishop': 'knightVsBishop',
  'Rook vs Minor': 'rookVsMinor',
  'Minorvs Rook': 'minorVsRook',
  'Rook vs Two Minors': 'rookVsTwoMinors',
  'Two Minors vs Rook': 'twoMinorsVsRook',
  'Queen vs Rook': 'queenVsRook',
  'Queen vs Two Rooks': 'queenVsTwoRooks',
  'Two Rooks vs Queen': 'twoRooksVsQueen',
  'Queen vs Rook and Minor': 'queenVsRookMinor',
  'Rook and Minor vs Queen': 'rookMinorVsQueen',
  'Rook and Minor vs Rook': 'rookMinorVsRook',
  'Pawn vs Knight': 'pawnVsKnight',
  'Pawn vs Bishop': 'pawnVsBishop',
  'Pawn vs Rook': 'pawnVsRook',
  'Rooks and Minors': 'rooksAndMinors',
  'Queens and Minors': 'queensAndMinors',
  'Two Minors vs Two Minors': 'twoMinorsVsTwoMinors',
  'Pawn Endgame': 'pawnEndgame',
  'Rook Endgame': 'rookEndgame',
  'Queen Endgame': 'queenEndgame',
  'Rook vs Pawns': 'rookVsPawns',
  'Queen vs Pawns': 'queenVsPawns',
  'Bishop vs Pawns': 'bishopVsPawns',
  'Bishops Endgame': 'bishopsEndgame',
  'Knight vs Pawns': 'knightVsPawns',
  'Knights Endgame': 'knightsEndgame',
  advancedPawn: 'advancedPawn',
  backRankMate: 'backRankMate',
  capturingDefender: 'capturingDefender',
  clearance: 'clearance',
  deflection: 'deflection',
  discoveredAttack: 'discoveredAttack',
  doubleCheck: 'doubleCheck',
  fork: 'fork',
  interference: 'interference',
  intermezzo: 'intermezzo',
  mate: 'mate',
  attraction: 'attraction',
  pin: 'pin',
  promotion: 'promotion',
  quietMove: 'quietMove',
  sacrifice: 'sacrifice',
  skewer: 'skewer',
  trappedPiece: 'trappedPiece',
  xRayAttack: 'xRayAttack',
  zugzwang: 'zugzwang',
  // New Tower Themes
  'Rook vs Knight': 'rookVsKnight',
  'Bishop vs Bishop': 'bishopVsBishop',
  'Knight vs Knight': 'knightVsKnight',
  'Rook vs Bishop': 'rookVsBishop',
  'Queen vs Bishop': 'queenVsBishop',
  'Queen vs Knight': 'queenVsKnight',
}

export const getThemeTranslationKey = (theme: string): string => {
  return THEME_KEY_MAP[theme] || theme
}
